### ISSUE TITLE
Buffer named 1750208748756 always opens when I try to commit

### ISSUE THREAD

**Issue by plaidfinch** [kahole/vscode-magit#346]
Whenever I try to commit my changes from the magit status buffer, I am first faced with an unsaved buffer entitled '1750208748756', which is blank. Closing it requires confirming that I do not want to save its (empty) contents. Then, I can see the magit commit message buffer. This behavior persists despite uninstalling and reinstalling the edamagit extension. I honestly have no idea what could be causing this issue, but I'm happy to provide diagnostic information if you'd like to tell me what would be helpful. This has been bugging me for weeks!

**Comment by bofm** [comment]
I have the same issue. On MacOS. Is there any debug info I can grab to help to solve this issue?

**Comment by spookylukey** [comment]
I think this may be fixed in v0.6.68, please re-open if that isn't the case. Thanks!

**Comment by plaidfinch** [comment]
This is fixed! Thank you! I'm so glad I can go back to using edamagit :)

**Comment by smarmit** [comment]
Hi. Unfortunately I still see this behavior with 0.6.68, but only on multi-project workspaces. I've tried a few settings without luck.

**Comment by danmilon** [comment]
@smarmit check the linked PR (#362).

**Comment by spookylukey** [comment]
This should have been fixed by #362, available in 0.6.69
